import { FormEvent, useState } from "react"
import Head from 'next/head'
import Link from 'next/link'
import axios from "axios";
import InputGroup from "../../components/InputGroup";
import { useRouter } from 'next/router'
import { useAuthState } from "../../context/auth";



export default function Register() {

    const router = useRouter()
    const { authenticated } = useAuthState()
    if (authenticated) router.push('/')
    
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('')
    const [username, setUsername] = useState('')
    const [agreement, setAgreement] = useState(false)
    const [errors, setErrors] = useState<any>({})

    const submitForm = async (event: FormEvent) => {
        event.preventDefault();

        if (!agreement) {
            setErrors({ ...errors, agreement: 'You must agreet to T&Cs' })
            return
        }
        try {
            await axios.post('/auth/register', {
                email, password, username
            })
            router.push('/login')
        } catch (err) {
            setErrors(err.response.data)

        }
    }

    return (
        <div className="flex bg-white">
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="h-screen bg-center bg-cover w-36"
                style={{ backgroundImage: "url('/images/bricks.jpg')" }}>
            </div>

            <div className="flex flex-col justify-center pl-6">
                <div className="div w-70">
                    <h1 className="mb-2 text-lg font-medium">Sign Up</h1>
                    <p className="mb-10 text-xs">
                        By continuing, you agree to our user agreement and privacy policy
                    </p>
                    <form onSubmit={submitForm}>
                        <div className="mb-6">
                            <input type="checkbox"
                                checked={agreement}
                                onChange={e => setAgreement(e.target.checked)}
                                className="mr-1 cursor-pointer" id="agreement" />
                            <label htmlFor="agreement" className="text-xs cursor-pointer">
                                I agree to get emails about cool stuff on Readit
                            </label>
                            <small className="block font-medium text-red-600">{errors.agreement}</small>
                        </div>
                        <InputGroup
                            classname="mb-2"
                            type="email"
                            value={email}
                            setValue={setEmail}
                            placeholder="Email"
                            error={errors.email}
                        />
                        <InputGroup
                            classname="mb-2"
                            type="username"
                            value={username}
                            setValue={setUsername}
                            placeholder="Username"
                            error={errors.username}
                        />
                        <InputGroup
                            classname="mb-4"
                            type="password"
                            value={password}
                            setValue={setPassword}
                            placeholder="Password"
                            error={errors.password}
                        />
                        <button
                            className="w-full py-2 mb-4 text-xs font-bold text-white uppercase bg-blue-500 border border-blue-500 rounded">
                            Sign Up
                        </button>
                    </form>
                    <small>
                        Already a Readitor?
                        <Link href="/auth/login">
                            <a className="ml-1 text-blue-500 uppercase">Log In</a>
                        </Link>
                    </small>
                </div>
            </div>

        </div>
    )
}